### ISSUE TITLE
Drawer does not scroll when content spans past screen height

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-drawer#17]
### Please verify the version of auro-drawer you have installed

1.0.8

### Please describe the bug

1. Create an auro-drawer component with content that spans past the screen height (or height of the drawer)
2. Open the drawer
3. See that you are unable to scroll within the drawer to see the content past the screen

<img width="527" alt="image" src="https://github.com/AlaskaAirlines/auro-drawer/assets/43892293/567d2205-9a1c-43f6-9bef-aacb4d1478bd">

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

When drawer content spans longer than the screen height (or drawer's max height), the drawer becomes scrollable.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Additional context

The bug is not reproducible on the deprecated auro-interruption drawer component.

I opened a similar bug in the auro-dialog component as well.

### Exit criteria

When drawer content spans longer than the screen height (or drawer's max height), the drawer becomes scrollable.

**Comment by Patrick-Daly-AA** [comment]
Same fix needed here as was applied here: https://github.com/AlaskaAirlines/auro-dialog/issues/15

Will retest and implement fix.

**Comment by Patrick-Daly-AA** [comment]
Issue still occurs after the related issues is fixed.  more investigation is needed.

**Comment by gusnaughton** [comment]
Issue is still occuring with the latest version 1.0.8. @Patrick-Daly-AA is there an estimated fix on this? I have also tested and 1.0.0 of @aurodesignsystem/auro-drawer has this issue.

**Comment by gusnaughton** [comment]
https://github.com/AlaskaAirlines/auro-drawer/assets/7005799/e25f2989-494a-4da9-b4bc-7b25800843d8

This is particularily impactful on seat map use cases
