### ISSUE TITLE
Close "x" button not displaying in default drawer

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-drawer#30]
### Please verify the version of auro-drawer you have installed

2.0.1

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/drawer
2. Click button "Open Default Drawer"
3. Look towards top right corner of the drawer
4. Notice missing "x" icon that is used to close the drawer

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

X button appears on open drawer

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

X button appears on open drawer

**Comment by jason-capsule42** [comment]
This is related to the issue with the sizing bug in auro-icon.
